# Generated by Django 4.2.4 on 2023-09-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_profile_picture_user_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
