# Generated by Django 4.2.4 on 2023-09-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploadplants',
            name='image',
        ),
    ]
