# Generated by Django 4.2.4 on 2023-09-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_useruploadplants_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadplants',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
